name: Setup Node and install dependencies
description: "Install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "npm"

    - name: Update packages
      run: npm update
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
