name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: disc
        path: ${{ github.workspace }}/dist

    - name: Upload S3
      uses: shallwefootball/upload-s3-action@master
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'dist'