name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:3000'

  lhci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-node

    - name: Build
      run: npm run build

    - name: Lighthouse run
      run: |
        npm install -g @lhci/cli@0.3.x
        lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
      env:
        LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

