name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    
    - name: Update packages
      run: npm update

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Lighthouse run
      run: |
        npm install -g @lhci/cli@0.3.x
        lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
      env:
        LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:3000'

