name: E2E test on Chrome

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:3000'

    - name: Upload test screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        if-no-files-found: ignore

    - name: Upload test videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
        if-no-files-found: ignore

  download:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download test screenshots
        uses: actions/download-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Download test videos
        uses: actions/download-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos