name: E2E test on Chrome

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:3000'

    - name: Set code coverage commit status
      run: npx -p check-code-coverage set-gh-status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
