name: E2E test on Chrome

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:3000'

    - name: Upload test screenshots
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: ${{ github.workspace }}/cypress/screenshots
        if-no-files-found: ignore

    - name: Upload test videos
      uses: actions/upload-artifact@v3
      with:
        name: cypress-videos
        path: ${{ github.workspace }}/cypress/videos
        if-no-files-found: ignore